apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: lbloader
    app.kubernetes.io/name: server
  name: lbloader
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: lbloader
    app.kubernetes.io/name: server
  type: NodePort
